### ISSUE TITLE
Timelines only work in English

### ISSUE THREAD

**Issue by Lusaca87** [xpdota/event-trigger#118]
Im not sure if i have done anything wrong with it but im a little bit confsued.

I testet this app and it looks like it runs even with WSS. it connects fine.
HP and stuff will be shown correctly but if i start a fight like e12s the timeline will not be shown infight.

if i i enable "show pre pull" it will be shown, but it dont runs. (lines stand still and show nothing)

i have startet act and trigg as admin and normal and mixed. nothing helps. 

Edit: maybe it doesnt support any other language then english? because i use a german client

**Comment by Delta87** [comment]
A picture to show my issue.
![image](https://user-images.githubusercontent.com/17047430/188054649-9c5ee372-c38a-4697-953e-10e4e61ceefb.png)

**Comment by Delta87** [comment]
A picture to show my issue.
![image](https://user-images.githubusercontent.com/17047430/188054755-efdab13f-243a-424c-b6e7-b9bafdce3961.png)

**Comment by xpdota** [comment]
You're probably right about the German client. I know Cactbot has some way of translating the timelines. I'll have to look into that.

**Comment by Delta87** [comment]
It its the german client, after i switch to english for a test, it wors pretty fine!

**Comment by xpdota** [comment]
Timeline translation support has been added
