### ISSUE TITLE
Is it possible to change the text cardinal, intercardinal on triggers?

### ISSUE THREAD

**Issue by dambyul** [xpdota/event-trigger#121]
I'm a user from korea and I'm using callout triggers by changing the callout text to korean. Changing the Arena Position text function is very useful(like changing it to 1,2,3,4,A,B,C,D). But I can not change some values like cardinal, intercardinal on P8S 1P.  Is there a way to change these text?

**Comment by xpdota** [comment]
Not currently, but I'll think about how to add it.

**Comment by xpdota** [comment]
Okay, I have a branch for this now (you can check out `global-callout-replacements` if you want to take a look). It looks like this, and lets you do a find/replace over all TTS and/or text:

![image](https://user-images.githubusercontent.com/14287379/193480459-f61f88e0-cb9e-46ca-991f-861f91c8f432.png)

**Comment by xpdota** [comment]
This has been released

**Comment by xpdota** [comment]
There's another alternative to the global replacements.

You can remap an individual parameter like so. In this example, the default wyrmhole "Any Spot", "In Front", "Behind You", "On You" are remapped to custom values:

```groovy
{["Any Spot": "Pick Spot", "In Front": "West", "Behind You": "East", "On You": "South"][where]}
```
