### ISSUE TITLE
TTS is not working for DoT/Buff tracker or CD tracker, but is working for Timeline

### ISSUE THREAD

**Issue by Qunka724** [xpdota/event-trigger#125]
Yeah so I'm on the current update as of this post, and today I noticed this issue. The "Test TTS" button in the general tab works and so do some custom timeline events I have created, but I wasn't getting any TTS on my DoT or CD trackers. Overlay plugin 0.18.2.0.

**Comment by xpdota** [comment]
Update OverlayPlugin, see https://overlayplugin.github.io/OverlayPlugin/fork_update.html

**Comment by Qunka724** [comment]
Thank you for this! Sorry I was trying to fix it between pulls and I saw the pins in discord - I guess I read it to fast to realize there was a procedure that needed to be followed.
