### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by quisquous** [xpdota/event-trigger#127]
If you are including cactbot files directly into event-trigger, then it is at least redistributing cactbot if not also a derivative work, and thus is not being licensed properly.  https://github.com/quisquous/cactbot/blob/main/LICENSE

**Comment by xpdota** [comment]
How do you want me to accredit it? I see you have a section at the bottom with a list of bundled things, you want the same kind of thing here?

**Comment by xpdota** [comment]
Is this okay? https://github.com/xpdota/event-trigger/blob/master/LICENSE

**Comment by quisquous** [comment]
Thanks!

**Comment by quisquous** [comment]
Also, xivapi is xivapi, all lowercase.
