### ISSUE TITLE
Is there any way to import cactbot triggers?

### ISSUE THREAD

**Issue by itonohito** [xpdota/event-trigger#128]
I'd like to import cactbot triggers for old dungeons and general triggers (provoke/shirk etc) but didn't found, how to do it.
Is there any comfortable way to do it?

**Comment by xpdota** [comment]
Directly import, no, they're a different format. But it's generally fairly easy to remake them, e.g.:

```ts
    {
      id: 'P8S Conceptual Tetraflare Quadruped',
      type: 'StartsUsing',
      // 7915 normally
      // 7916 during Blazing Footfalls
      netRegex: NetRegexes.startsUsing({ id: '7916', source: 'Hephaistos', capture: false }),
      durationSeconds: 20,
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Partner Stacks',
          de: 'Mit Partner sammeln',
          fr: 'Package avec votre partenaire',
          ja: '2人頭割り',
          ko: '2인 쉐어',
        },
      },
    },
```

would be (this is a different version of the UI that isn't released yet, but the important parts are the same):

![image](https://user-images.githubusercontent.com/14287379/191522398-ff4135f8-4953-44c3-b232-7525f490bc45.png)

I can see about making something to auto-import the simple triggers, but anything with non-trivial conditions or logic probably wouldn't be auto-importable. What I plan to do at some point anyway is to expose a Websocket server, allow the user to connect Cactbot to that instead, and then you'd have all your callouts in one place.

**Comment by itonohito** [comment]
thanks, will try.
