### ISSUE TITLE
Customised timelines dont work properly

### ISSUE THREAD

**Issue by ligmalominsa** [xpdota/event-trigger#130]
Hi ive been trying to edit timelines to show my mitigation but the timelines dont show reliably and sometimes just stop midfight 

here's the triggevent log and act log 
[triggevent.log](https://github.com/xpdota/event-trigger/files/9657573/triggevent.log)
[Network_26606_20220927.log](https://github.com/xpdota/event-trigger/files/9657580/Network_26606_20220927.log)

**Comment by xpdota** [comment]
Is there a particular zone that it wasn't working right in? Or was it all of them?

**Comment by xpdota** [comment]
Do you have the "hide chat log for privacy" setting enabled? I believe this interferes with timelines because it never sees the "Engage!" line.

This seems to be a problem specific to a few duties judging by your log. I'll update these in cactbot so that this isn't an issue.

**Comment by ligmalominsa** [comment]
thanks for helping i dont have the hide chat log for privacy on but ill try the your recommendation and let you know when im back from work.

**Comment by xpdota** [comment]
Oh, I see. It was probably a pull with no countdown? So there would be no "Engage" line.

**Comment by ligmalominsa** [comment]
yeah there was no countdown when it didint work so that may be the issue

**Comment by xpdota** [comment]
This should work now. Can you give it another try?

**Comment by xpdota** [comment]
Seems to have been fixed, closing.
