### ISSUE TITLE
Selectively enable TTS for fights/callouts

### ISSUE THREAD

**Issue by RoarkGit** [xpdota/event-trigger#163]
Right now TTS is enabled globally, and then callouts can be disabled individually. If I want TTS for only one mechanic in a fight, I currently need to enable TTS globally and then disable all other callouts one by one, including any additional fights for which I might use triggevent. It would be nice if there was an option to disable individual TTS callouts by default so that they could be selectively enabled instead.

**Comment by xpdota** [comment]
![image](https://user-images.githubusercontent.com/14287379/207700011-5875744e-be8e-4e4e-8f51-fbbbb0e41fc0.png)

Does something like this do what you need? You'd be able to enable the group but click the "disable all" button to disable all the individual checkboxes.

**Comment by RoarkGit** [comment]
Would that just disable TTS for all? The use case is that I want all enabled callouts (for text notice, sounds, etc.) but TTS disabled for all the callouts.

**Comment by xpdota** [comment]
Is this closer to what you want? 

![image](https://user-images.githubusercontent.com/14287379/208213835-9387bbc3-533d-4899-8f9e-f25ad77d2c0e.png)

The "Enable By Default", "Enable TTS By Default", and "Enable Text By Default" options will set the default for the callouts as a whole, the TTS portion, and the visual portion. Anything not explicitly customized will follow the new setting. Anything that has been explicitly customized will have the pink coloring.

**Comment by RoarkGit** [comment]
As far as I can tell that is exactly the functionality I was looking for.

**Comment by xpdota** [comment]
Ok, it's available over on the master branch. I'll release it fully soon.
