### ISSUE TITLE
Party Cooldown Tracker Style

### ISSUE THREAD

**Issue by rushtothesun** [xpdota/event-trigger#19]
Could you consider making a style similar to ZeffUI?

![this](https://raw.githubusercontent.com/Zeffuro/ZeffUI/master/screenshots/raidbuffs.png)

The current tracker is a bit small and blurry on my screen

**Comment by xpdota** [comment]
Would you mind posting a screenshot of it? I'm curious as to why it would be blurry.

I can certainly look at adding more styles.

**Comment by rushtothesun** [comment]
https://puu.sh/IEnZ3/294a04645e.jpg

https://puu.sh/IEnZc/1fbfe704c1.jpg

**Comment by xpdota** [comment]
Been a while, but this is finally available for testing. Went with more of a JobBars style: https://github.com/xpdota/event-trigger/pull/175 

Feel free to use none of the other party list components if you plan to overlay it on top of the in-game party list rather than using the custom party list.

**Comment by xpdota** [comment]
This has been released
