### ISSUE TITLE
Skip to next matching log line

### ISSUE THREAD

**Issue by amki** [xpdota/event-trigger#2]
Could you implement a feature that skips to (or x before) a log line matching a trigger or matching a regex?

That would be super helpful to watch combatants change and determine timings.

**Comment by xpdota** [comment]
I'm thinking what I could do is add a button at the end of your filters for whatever tab you're on, that will advance until you get another line (ACT line or normal event) that passes your filters. Would that do more or less what you're looking for?

**Comment by amki** [comment]
That would also be fine, yes. It's hard to watch several events unfold to get how getCombatants develops while manually jumping around the session. :3

**Comment by xpdota** [comment]
Merged to master/alpha. You can change `updater.properties` to point to the alpha branch, or wait for stable release.
