### ISSUE TITLE
Triggerevent won't start

### ISSUE THREAD

**Issue by AlkaidG** [xpdota/event-trigger#203]
Followed the installation instructions like I did before but now I am getting the follwoing error

You should report this as a bug and include log files in C:\Users\Shanur Islam\AppData\Roaming\triggevent as well as this error message.

You can also try moving/renaming the properties files in that directory to see if this error is being caused by a problem with your settings.

java.lang.NoSuchMethodError: 'gg.xp.xivsupport.persistence.PropertiesFilePersistenceProvider gg.xp.xivsupport.persistence.PropertiesFilePersistenceProvider.inUserDataFolder(java.lang.String)'
	at gg.xp.xivsupport.sys.XivMain.masterInit(XivMain.java:125)
	at gg.xp.xivsupport.gui.GuiMain.lambda$main$0(GuiMain.java:129)
	at gg.xp.xivsupport.gui.util.CatchFatalError.run(CatchFatalError.java:22)
	at gg.xp.xivsupport.gui.GuiMain.main(GuiMain.java:125)
	at gg.xp.xivsupport.gui.GuiLaunch.main(GuiLaunch.java:8)

Can't even start treggerevent
[triggevent.log](https://github.com/xpdota/event-trigger/files/10366768/triggevent.log)

**Comment by xpdota** [comment]
Sorry for the errors. Could you please try running the updater (triggevent-upd.exe)?

**Comment by AlkaidG** [comment]
It's working now. Cheers
