### ISSUE TITLE
Feature Request: Create easy trigger from HeadMarkerEvent

### ISSUE THREAD

**Issue by Moo-Chicken** [xpdota/event-trigger#234]
The new extreme trial has a tankbuster that hits two players but does not target players using the AbilityCastStart type and instead uses a HeadMarkerEvent. Would it be possible to have it make an easy trigger that would call out the targets or put a marker on their head?

![image](https://user-images.githubusercontent.com/66681191/213239808-bc739bdf-15e4-45c1-ad0e-a9a0e724e380.png)

![image](https://user-images.githubusercontent.com/66681191/213240129-88baf127-629f-4b5e-b836-a922aa493ed7.png)

**Comment by xpdota** [comment]
This is doable, the issue is that all the newer content uses the "offset headmarker" stuff, but that's just a liability for older content. I might have to make it so you can pick which one you want when making the trigger.

**Comment by xpdota** [comment]
Okay, I have it up on the "headmarker-easy-triggers" if you want to try it out.
