### ISSUE TITLE
[BUG] RDM Contre Sixte CD

### ISSUE THREAD

**Issue by x3nobite** [xpdota/event-trigger#295]
The Contre Sixte CD is 45 secs in the Library, but in cooldown timers 35 secs.
Havent manage to change myself (think is not intended though) thats why I added this issue ticket.
Cheers

**Comment by natyusha** [comment]
[Contre Sixte](https://ffxiv.gamerescape.com/wiki/Contre_Sixte) is 45s until modified by the [Red Magic Mastery](https://ffxiv.gamerescape.com/wiki/Red_Magic_Mastery) trait at level 74 to be 35s.

**Comment by xpdota** [comment]
Yeah, the library tab shows the values without traits.
