### ISSUE TITLE
Target marker sign type varies by client

### ISSUE THREAD

**Issue by 4i7** [xpdota/event-trigger#330]
Hi, please confirm the title and the following information.
For example, JP clients use stop1 instead of Ignore1, etc.
This only pertains to the error messages I have identified and is a potential problem for clients in other languages.
I'm not sure of the details, though.
https://na.finalfantasyxiv.com/lodestone/playguide/db/text_command/4348eed9de5/
https://jp.finalfantasyxiv.com/lodestone/playguide/db/text_command/4348eed9de5/
best regards

**Comment by xpdota** [comment]
I need to check all the languages, but the "JP/KR Client Mode" setting will change 'ignore' to 'stop' which should work around it for the time being.

**Comment by 4i7** [comment]
Thank you for your careful review.
I will check on the settings.
