### ISSUE TITLE
Opacity slider doesn't slide, all overlays are solid black

### ISSUE THREAD

**Issue by dlm21** [xpdota/event-trigger#344]
Very cool thing you've made here!
I'm on Linux and using KDE+Wayland, Radeon GPU drivers, java 17.0.6.
My issue is that all the overlays have a solid opaque black background.
They do stay on top of the game window, but whether on the monitor with the game or on the other monitor, I can't see through the overlays. I'm not sure if this is a limitation of Java on Wayland, or something else. I'll be glad to test stuff or provide more info.

The terminal shows this when I try to drag the slider:

00:56:12.672 [AWT-EventQueue-0] INFO  g.x.x.p.PropertiesFilePersistenceProvider:114 - Setting changed: xiv-overlay.window-pos.job-specific-overlay.opacity -> 1.0
00:56:12.798 [AWT-EventQueue-0] INFO  g.x.x.p.PropertiesFilePersistenceProvider:114 - Setting changed: xiv-overlay.window-pos.job-specific-overlay.opacity -> 1.0
00:56:12.872 [AWT-EventQueue-0] INFO  g.x.x.p.PropertiesFilePersistenceProvider:114 - Setting changed: xiv-overlay.window-pos.job-specific-overlay.opacity -> 1.0
00:56:12.996 [AWT-EventQueue-0] INFO  g.x.x.p.PropertiesFilePersistenceProvider:114 - Setting changed: xiv-overlay.window-pos.job-specific-overlay.opacity -> 1.0
00:56:13.081 [AWT-EventQueue-0] INFO  g.x.x.p.PropertiesFilePersistenceProvider:114 - Setting changed: xiv-overlay.window-pos.job-specific-overlay.opacity -> 1.0
00:56:13.202 [AWT-EventQueue-0] INFO  g.x.x.p.PropertiesFilePersistenceProvider:114 - Setting changed: xiv-overlay.window-pos.job-specific-overlay.opacity -> 1.0

Looking through the source, perhaps something like this ye olde post would help ? However xprop -root shows _NET_WM_WINDOW_OPACITY is supported, so maybe not~
https://stackoverflow.com/questions/27405356/kwin-and-java-transparency

**Comment by xpdota** [comment]
The opacity slider is disabled on non-Windows since it doesn't work. It was actually resulting in the exact problem you seem to be having.

I'm not sure what would be causing your other issue - I just tried it on KDE+Wayland (though it's with an un-accelerated virtio GPU) and the transparency works fine:

![image](https://user-images.githubusercontent.com/14287379/224768993-3bf3224a-f47d-4a83-a222-4f91ae1a40fa.png)

**Comment by dlm21** [comment]
After messing around with the settings in Pluging Settings, the overlays that support theming were able to be made transparent using the background color to transparent, so it does appear to work for things like Custom Party Overlay, Skill Hit Tracker and Callout Text. The rest are all still stuck with the solid black background. I'll test more later today after work with different desktop environments / window managers / xorg vs wayland etc and see if there's any difference.

![Screenshot_03-13-2023_1](https://user-images.githubusercontent.com/1882342/224801597-6c1eab83-1729-4041-b496-543c73bbde74.png)

**Comment by dlm21** [comment]
Ok, so after testing on Xorg and Wayland, Plasma, Gnome and Cinnamon, it appears the issue is somehow related to my double monitors and not Xorg/Wayland/DE/WM/etc. Any overlays that start on the "primary" display are transparent, however any that start on the secondary monitor and I drag over are solid black. The solution I'm happy with is to edit the starting X position beyond the monitor on my left (secondary display) so the overlays are drawn on the primary display in front of me. I have no idea why this is or where that bug is, but I can start really testing this stuff now at least. 
Thanks for taking the time to look into it, and thanks for making this!
