### ISSUE TITLE
Overlays are not actually visible

### ISSUE THREAD

**Issue by RoarkGit** [xpdota/event-trigger#345]
I'm running FFXIV on Fedora 37 in GNOME on Wayland with an AMD 7900 XTX. I am not able to actually see the overlays anywhere when they are enabled, but I can actually see a bunch of overlay windows that were created when I hit Alt+Tab. Going into edit mode or manually changing the coordinates doesn't seem to have any effect, either.

![image](https://user-images.githubusercontent.com/34554573/224802297-95d31d2c-96f1-4102-bb00-49e81967be9c.png)

**Comment by dlm21** [comment]
Are you sure they aren't behind the game ? I have same video card, CachyOS KDE+Wayland, and have kwin rules to ensure the game doesn't go "full screen", which apparently is a thing in wayland, if it's taking up the full size it acts like it's the only thing. Try to set it in windowed mode and see if the overlays show up on the desktop behind the game.

**Comment by RoarkGit** [comment]
@dlm21 That was a really good idea but unfortunately that's not what's going on.. even when setting it to strictly windowed mode I cannot actually see the overlays anywhere.

**Comment by RoarkGit** [comment]
> Are you sure they aren't behind the game ? I have same video card, CachyOS KDE+Wayland, and have kwin rules to ensure the game doesn't go "full screen", which apparently is a thing in wayland, if it's taking up the full size it acts like it's the only thing. Try to set it in windowed mode and see if the overlays show up on the desktop behind the game.

I wanted to necro this thread; I've switched to KDE recently and found that what you suggested with KWin scripts might work, as I can now actually see the overlays behind the window. How did you configure this to force Fullscreen off? I've tried matching the Window name and setting Fullscreen: Force (No) but it seems to always reset to Yes whenever the window is focused.
