### ISSUE TITLE
Cooldown Tracker Extension

### ISSUE THREAD

**Issue by shinyrukii** [xpdota/event-trigger#35]
Recently came across this and actually like the cooldown tracker, especially for charged actions.
Since the cooldown list seems to be missing a few sets of actions, would it be possible to add those manually in future?

Additionally, I was wondering if it would be considered to add sound files to play as alternative to TTS callouts for DoT/Cooldown tracker callouts. I'd love to swap from other trackers to this since due to the visuals, but would prefer sounds over TTS.

SR

**Comment by xpdota** [comment]
Hmm, I haven't planned for audio over TTS, but I'll think about it.

For getting the list of cooldowns completed, since there's a finite number of abilities, I'd rather just finish out the list so that nobody has to manually enter anything. If there's any missing, I just need the ability names+IDs and I can add them to the list.

**Comment by ZingKaruKek** [comment]
Hey there! Your charges under BasicCalloutEvent for Onslaught/Plunge/etc. (all of them from what I can really tell) aren't lining up properly under a 30 second window at all and some are doing duplicate callouts when there's still ample amounts of time left on their second stack timers. (Prime example being Shadowbringers is calling out the second stack being ready at 20seconds left on the CD still.)

Hope this bit of tinkering helps!

**Comment by xpdota** [comment]
Ah, true, they were never meant to really be used for charge-based abilities. I'll see what I can do to make it work a little better.

**Comment by ZingKaruKek** [comment]
If it wasn't meant to be used that way then it's not a huge deal.

Truly appreciate everything you've done so far, thank you so much.

**Comment by xpdota** [comment]
Actually, I think I have it working, go ahead and update again and see if it works now. It should only call when you're about to be capped.
