### ISSUE TITLE
Feature Request: Changing scaling on timeline overlay bars

### ISSUE THREAD

**Issue by Eleida** [xpdota/event-trigger#359]
Right now an empty bar on the timeline overlay means a mechanic is over 60 seconds away, and at 60s it will start to fill, but that number cannot be customized, even if the "[X] Seconds in Future" setting is lower than 60.

For example, right now I only show events once they're 20s away. This means that I'm really only using the rightmost 1/3 of each bar, and the last 5s or so (which are the most important for precise timing) are only a few pixels wide.
![javaw_KlYZtIAH7L](https://user-images.githubusercontent.com/129000727/227798511-87065432-40d9-4862-8aa3-49d645f39534.png)

**Comment by xpdota** [comment]
I added a new setting to the timeline tab for this, you can try it on the `timeline-bar-basis-setting` branch.

**Comment by Eleida** [comment]
Thank you so much!!! ♥
