### ISSUE TITLE
About in-game command

### ISSUE THREAD

**Issue by medivhmichaelis** [xpdota/event-trigger#365]
hello,i would like to know how i can perform a in-game command with easy-trigger using PostNamazu.
thank you.

**Comment by xpdota** [comment]
Hi, I'll add an easy trigger action for this.

**Comment by medivhmichaelis** [comment]
oh,much thanks

**Comment by xpdota** [comment]
Done
You can use it like this:
![](https://user-images.githubusercontent.com/14287379/229845743-468cdbe1-6acb-4d5e-b2d5-197989c7d2ca.png)

**Comment by medivhmichaelis** [comment]
excellent.
thanks for the wanderful project,team
