### ISSUE TITLE
Bug: Clone Event not Copying Job Settings

### ISSUE THREAD

**Issue by Eleida** [xpdota/event-trigger#380]
Cloning an event does not clone the settings from the "jobs" column, which I assume it's supposed to (if it's not supposed to... can it? pls?)

Also I'm not sure if there's a system reason for the word "copy" being appended to the text when you clone an event, but needing to edit it out every time is a small but frustrating time waster. Could that be removed if it isn't needed? (If the events are truly identical -- which they should be with the jobs difference above being fixed -- then there's no need to know which is the clone and which is the original.)

**Comment by xpdota** [comment]
Also have this one fixed on the `timeline-improvements` beta branch.
