### ISSUE TITLE
Add Linux support for Local TTS

### ISSUE THREAD

**Issue by VinnyVynce** [xpdota/event-trigger#382]
Hi, currently the local TTS [use powershell.exe for the local TTS](https://github.com/xpdota/event-trigger/blob/53b88be13e2dca5d7b1e01e8e0d316cd6444e9ed/xivsupport/src/main/java/gg/xp/xivsupport/speech/PowerShellSpeechProcessor.java#L58) (using MS Speach)
Would it possible to add an option through a configuration file or the GUI itself to launch any programs that we want.
For example I could set:
```
/usr/local/bin/mimic -voice ap -t %s
``` 
where %s would be the text. That way we could have linux support as well for this feature.
Thanks!

**Comment by xpdota** [comment]
![image](https://user-images.githubusercontent.com/14287379/236313736-9ef25520-c785-4eec-bb69-b44b9c2b0efc.png)

Does this work for you? It's available on master now.

**Comment by VinnyVynce** [comment]
Hi @xpdota, I can confirm the test TTS works perfectly on my machine. I plan to raid a bit later tonight, I'll keep you updated if everything works fine.
Thanks a lot and good job! 👍🏻

**Comment by VinnyVynce** [comment]
I can confirm the local TTS overwrite worked perfectly yesterday. I used it with iinact and it worked perfectly for the entire night.
Thanks again, you can close the issue.

**Comment by xpdota** [comment]
Released
