### ISSUE TITLE
Bug report-General translation section need

### ISSUE THREAD

**Issue by algo23-Shuairui** [xpdota/event-trigger#390]
https://github.com/xpdota/event-trigger/pull/178
In this pull, I found that the general translation section from the following translation.ts did not take effect in the timeline module of the event trigger, which resulted in many instances where the triggering initial event could not take effect, involving approximately 85 timelines. May I ask how to solve it?

https://github.com/quisquous/cactbot/blob/bb262c1584a5b42b76c4e14efae843a2ffbba4f2/resources/translations.ts
This is the general translation section from cactbot.

**Comment by algo23-Shuairui** [comment]
![209425472-0e284004-d4a5-45b5-b540-2d9269e8a073](https://github.com/xpdota/event-trigger/assets/125130842/9cf67912-f8c7-4cad-a1f9-cc7f1e1f924f)
For example, this engage should be "战斗开始" in timeline just like in cactbot timeline.

**Comment by xpdota** [comment]
I think I see the problem. The general timeline translations are in [comon_replacements.ts](https://github.com/quisquous/cactbot/blob/main/ui/raidboss/common_replacement.ts) so I need to also consider that.

**Comment by algo23-Shuairui** [comment]
> 

The problem caused by translation mainly occurs in the 4-person version, which is not obvious in the 8-person copy. Because I think your work is very useful, I plan to completely replace the timeline of Cactbot with this framework. Therefore, in today's four person test, I found that this issue is very common. I have roughly counted dozens of older four people who used locked areas to correct the timeline, which can cause the timeline to completely fail to work, such as:
![A](https://github.com/xpdota/event-trigger/assets/125130842/946c71fa-701b-4305-9ec9-c4e443c4829f)
![B](https://github.com/xpdota/event-trigger/assets/125130842/a3845775-dc8d-42f3-8789-7b524de807ee)
![C](https://github.com/xpdota/event-trigger/assets/125130842/3ec933d8-c4cd-4666-9ba3-81503db011f4)

We can see these general translation sections are often the **only** thing to correct the timeline at their postion.
Very common bug.

**Comment by xpdota** [comment]
I think I know how to fix it. Does this look correct?

![image](https://github.com/xpdota/event-trigger/assets/14287379/e17b6115-ea0e-4e4f-bf08-4f3530bb0d78)
