### ISSUE TITLE
ACTWS not working when using SSL

### ISSUE THREAD

**Issue by Akurosia** [xpdota/event-trigger#4]
For other overlays etc i need to have SSL enabled, but as soon as SSL is enabled, the Programm does not recognize the ACTWS session.

**Comment by xpdota** [comment]
I'll add a couple of new settings to the advanced tab, so you can specify your wss:// url and bypass verficiation for self-signed:

![image](https://user-images.githubusercontent.com/14287379/147711331-726393a9-1144-48e6-93a0-cdd9ff9eb15b.png)
