### ISSUE TITLE
using automarker in easy triggers or somewhere else

### ISSUE THREAD

**Issue by dambyul** [xpdota/event-trigger#68]
Hello, I'm using this addon when doing DSR. I want to make triggers that can use automarkers (like in jail plugin). is there a way that I can use automarkers in some other triggers? 

Thank you!

**Comment by xpdota** [comment]
From the UI, no, the trigger maker only does basic callouts/text.

In the code, absolutely. I can look into it when I actually get progged to that point (or have a good log file + descriptions of who should get marked with what). The short version is that you'd basically just copy JailSolver and JailGui and change the handleJailCast method to whatever the condition for marking someone is. Then, you'd get the personal callout + automarks + GUI for configuring priority as with the jails.

**Comment by dambyul** [comment]
Thanks for your fast comment. I'll edit my handleJailCast method for my case. I think It will be awesome if there is a custom jailsolver kind of thing that can be customizable because there are so many random stuffs in DSR. (like dooms or debuffs)

**Comment by xpdota** [comment]
Sounds good, might as well make a PR for what you got and I can clean it up and release it.

Don't forget the zone lock too.
