### ISSUE TITLE
Cannot enable "Triggevent_sub.dll"

### ISSUE THREAD

**Issue by BrakusTapus** [xpdota/event-trigger#84]
No matter where i place the .dll in the i always get this error, i've tried to redownload Triggevent, putting it on any place in the plugin list 
within ACT .
I made sure to extract the Zip (with the java in it) and adding the .dll through ACT and also by placing it in the %appdata%roaming/ACT/plugins and then using the browse feature and i tried adding the dll through the browse feature in ACT but i just can't seem to get it to work.

I dont know if there's something i forgot to do and i was hoping if someone here would know
![6OnNcDf](https://user-images.githubusercontent.com/38063721/175287261-62b0db04-db8a-4e26-90a5-abd07e345401.png)

**Comment by xpdota** [comment]
Ah, you have to leave it in the same folder as the rest of the Triggevent files. I'll add something to the documentation about this.

**Comment by BrakusTapus** [comment]
Can confirm that fixed the issue, and made me feel extra dumb cause i swear i tried that when trouble shooting.. regardless, thank you @xpdota!
