### ISSUE TITLE
DSR automarkers for p6

### ISSUE THREAD

**Issue by program-ui** [xpdota/event-trigger#90]
I am trying to find the DSR automarker for p6 wroth but I only managed to find the titan gaols automarker in triggevent instead. Where can I find the DSR automarker for p6 wroth in triggevent?

**Comment by xpdota** [comment]
Are you on the latest version? (check in Advanced > Updates)

**Comment by program-ui** [comment]
omg thank you so much, i thought I had the latest version since I just downloaded the recent releases.
